// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Data.Migrations
{
    [DbContext(typeof(TsubasaDbContext))]
    [Migration("20260113173443_AddIsCombinedToTechnique")]
    partial class AddIsCombinedToTechnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("backend.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("backend.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroundBallSkill")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HighBallSkill")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PassiveSkillId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Positions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamSkillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PassiveSkillId");

                    b.HasIndex("TeamSkillId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("backend.Models.PlayerVersionTechnique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TechniqueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TechniqueId");

                    b.HasIndex("PlayerId", "TechniqueId")
                        .IsUnique();

                    b.ToTable("PlayerVersionTechniques");
                });

            modelBuilder.Entity("backend.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("backend.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bonuses")
                        .HasColumnType("TEXT");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("backend.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("backend.Models.TeamSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TeamSkills");
                });

            modelBuilder.Entity("backend.Models.Technique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCombined")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaminaCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Techniques");
                });

            modelBuilder.Entity("backend.Models.Player", b =>
                {
                    b.HasOne("backend.Models.Skill", "PassiveSkill")
                        .WithMany()
                        .HasForeignKey("PassiveSkillId");

                    b.HasOne("backend.Models.TeamSkill", "TeamSkill")
                        .WithMany()
                        .HasForeignKey("TeamSkillId");

                    b.OwnsOne("backend.Models.PlayerStats", "Stats", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Block")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("CatchStat")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Dribble")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Energy")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Intercept")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Pass")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Power")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Punch")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Shot")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Speed")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Tackle")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Technique")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("PassiveSkill");

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("TeamSkill");
                });

            modelBuilder.Entity("backend.Models.PlayerVersionTechnique", b =>
                {
                    b.HasOne("backend.Models.Player", "Player")
                        .WithMany("PlayerTechniques")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Technique", "Technique")
                        .WithMany("PlayerVersions")
                        .HasForeignKey("TechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Technique");
                });

            modelBuilder.Entity("backend.Models.Skill", b =>
                {
                    b.HasOne("backend.Models.Player", null)
                        .WithMany("LatentSkills")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("backend.Models.Player", b =>
                {
                    b.Navigation("LatentSkills");

                    b.Navigation("PlayerTechniques");
                });

            modelBuilder.Entity("backend.Models.Technique", b =>
                {
                    b.Navigation("PlayerVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
