// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Data.Migrations
{
    [DbContext(typeof(TsubasaDbContext))]
    [Migration("20260221164031_MoveBallBonusFromTechniqueToTechType")]
    partial class MoveBallBonusFromTechniqueToTechType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("backend.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("backend.Models.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdvantageOverElementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdvantageOverElementId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("backend.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroundBallSkill")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HighBallSkill")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PassiveSkillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerBaseId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Positions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RarityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamSkillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ElementId");

                    b.HasIndex("PassiveSkillId");

                    b.HasIndex("PlayerBaseId");

                    b.HasIndex("RarityId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamSkillId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("backend.Models.PlayerBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PlayerBases");
                });

            modelBuilder.Entity("backend.Models.PlayerLatentSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("PlayerId", "SkillId")
                        .IsUnique();

                    b.ToTable("PlayerLatentSkills");
                });

            modelBuilder.Entity("backend.Models.PlayerVersionTechnique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TechniqueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TechniqueId");

                    b.HasIndex("PlayerId", "TechniqueId")
                        .IsUnique();

                    b.ToTable("PlayerVersionTechniques");
                });

            modelBuilder.Entity("backend.Models.Rarity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rarities");
                });

            modelBuilder.Entity("backend.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("backend.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bonuses")
                        .HasColumnType("TEXT");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("backend.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("backend.Models.TeamSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TeamSkills");
                });

            modelBuilder.Entity("backend.Models.TechType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AppliesHighBallBonus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AppliesLowBallBonus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TechTypes");
                });

            modelBuilder.Entity("backend.Models.Technique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCombined")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerBaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaminaCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TechTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerBaseId");

                    b.HasIndex("TechTypeId");

                    b.ToTable("Techniques");
                });

            modelBuilder.Entity("backend.Models.Element", b =>
                {
                    b.HasOne("backend.Models.Element", "AdvantageOver")
                        .WithMany()
                        .HasForeignKey("AdvantageOverElementId");

                    b.Navigation("AdvantageOver");
                });

            modelBuilder.Entity("backend.Models.Player", b =>
                {
                    b.HasOne("backend.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("backend.Models.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Skill", "PassiveSkill")
                        .WithMany()
                        .HasForeignKey("PassiveSkillId");

                    b.HasOne("backend.Models.PlayerBase", "PlayerBase")
                        .WithMany("Players")
                        .HasForeignKey("PlayerBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Rarity", "Rarity")
                        .WithMany()
                        .HasForeignKey("RarityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId");

                    b.HasOne("backend.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("backend.Models.TeamSkill", "TeamSkill")
                        .WithMany()
                        .HasForeignKey("TeamSkillId");

                    b.OwnsOne("backend.Models.PlayerStats", "Stats", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Block")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("CatchStat")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Dribble")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Energy")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Intercept")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Pass")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Power")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Punch")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Shot")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Speed")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Tackle")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Technique")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("Country");

                    b.Navigation("Element");

                    b.Navigation("PassiveSkill");

                    b.Navigation("PlayerBase");

                    b.Navigation("Rarity");

                    b.Navigation("Series");

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("TeamSkill");
                });

            modelBuilder.Entity("backend.Models.PlayerLatentSkill", b =>
                {
                    b.HasOne("backend.Models.Player", "Player")
                        .WithMany("PlayerLatentSkills")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Skill", "Skill")
                        .WithMany("PlayerVersions")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("backend.Models.PlayerVersionTechnique", b =>
                {
                    b.HasOne("backend.Models.Player", "Player")
                        .WithMany("PlayerTechniques")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Technique", "Technique")
                        .WithMany("PlayerVersions")
                        .HasForeignKey("TechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Technique");
                });

            modelBuilder.Entity("backend.Models.Technique", b =>
                {
                    b.HasOne("backend.Models.PlayerBase", "PlayerBase")
                        .WithMany("Techniques")
                        .HasForeignKey("PlayerBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.TechType", "TechType")
                        .WithMany()
                        .HasForeignKey("TechTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerBase");

                    b.Navigation("TechType");
                });

            modelBuilder.Entity("backend.Models.Player", b =>
                {
                    b.Navigation("PlayerLatentSkills");

                    b.Navigation("PlayerTechniques");
                });

            modelBuilder.Entity("backend.Models.PlayerBase", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Techniques");
                });

            modelBuilder.Entity("backend.Models.Skill", b =>
                {
                    b.Navigation("PlayerVersions");
                });

            modelBuilder.Entity("backend.Models.Technique", b =>
                {
                    b.Navigation("PlayerVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
